# Generated by Django 6.0.2 on 2026-02-19 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parfumello', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='description',
        ),
    ]
