# Generated by Django 6.0.2 on 2026-03-04 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parfumello', '0002_remove_note_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfume',
            name='display_photo',
            field=models.ImageField(blank=True, null=True, upload_to='display_photos/'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
