# Generated by Django 6.0.2 on 2026-03-04 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parfumello', '0003_perfume_display_photo_user_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfume',
            name='review',
            field=models.ManyToManyField(blank=True, related_name='perfumes', to='parfumello.userreview'),
        ),
    ]
