# Generated by Django 6.0.2 on 2026-03-23 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parfumello', '0005_userreview_created_at_alter_userreview_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfume',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
