# Generated by Django 6.0.2 on 2026-03-23 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parfumello', '0007_alter_perfume_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfume',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
