# Generated by Django 6.0.2 on 2026-03-25 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parfumello', '0008_alter_perfume_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfume',
            name='sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Unisex', 'Unisex')], default='Unisex', max_length=20),
        ),
    ]
