# Generated by Django 6.0.2 on 2026-03-25 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parfumello', '0009_perfume_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfume',
            name='sex',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('unisex', 'Unisex')], default='unisex', max_length=20),
        ),
    ]
