# Generated by Django 6.0.2 on 2026-03-29 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parfumello', '0010_alter_perfume_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfume',
            name='display_photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/display_photos/'),
        ),
    ]
