# Generated by Django 6.0.2 on 2026-03-29 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parfumello', '0012_alter_perfume_display_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfume',
            name='display_photo',
            field=models.ImageField(blank=True, null=True, upload_to='display_photos/'),
        ),
    ]
