# Generated by Django 6.0.2 on 2026-03-29 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parfumello', '0013_alter_perfume_display_photo'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userreview',
            unique_together={('perfume', 'user')},
        ),
    ]
