# Generated by Django 6.0.2 on 2026-04-06 18:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_old_users(apps, schema_editor):
    """Create auth.User records for every old parfumello.User, then remap
    existing UserReview rows to point at the new auth_user ids."""
    from django.contrib.auth.hashers import make_password

    OldUser = apps.get_model('parfumello', 'User')
    AuthUser = apps.get_model('auth', 'User')

    id_map = {}
    for old_user in OldUser.objects.all():
        auth_user, _ = AuthUser.objects.get_or_create(
            username=old_user.username,
            defaults={
                'email': old_user.email or '',
                'password': make_password(None),  # unusable — user must reset
                'is_active': True,
                'is_staff': False,
                'is_superuser': False,
            }
        )
        id_map[old_user.pk] = auth_user.pk

    # Remap review user_ids at SQL level (FK still points at old table here).
    # Fetch rows first, then update by PK to avoid cascading overwrites when
    # a new_id happens to equal another old_id.
    with schema_editor.connection.cursor() as cursor:
        cursor.execute('SELECT id, user_id FROM parfumello_userreview')
        rows = cursor.fetchall()
        for review_id, old_user_id in rows:
            if old_user_id in id_map:
                cursor.execute(
                    'UPDATE parfumello_userreview SET user_id = %s WHERE id = %s',
                    [id_map[old_user_id], review_id]
                )


def create_profiles_and_migrate_favorites(apps, schema_editor):
    """Create a Profile for every auth.User and carry over profile_pic +
    favorite_perfumes from the old parfumello.User records (via raw SQL to
    avoid M2M related_name conflicts between old User and new Profile)."""
    AuthUser = apps.get_model('auth', 'User')
    Profile = apps.get_model('parfumello', 'Profile')

    db = schema_editor.connection

    # Build username → (profile_pic, [perfume_ids]) from old tables
    with db.cursor() as cursor:
        cursor.execute('SELECT id, username, profile_pic FROM parfumello_user')
        old_users = {row[0]: {'username': row[1], 'profile_pic': row[2]} for row in cursor.fetchall()}

        cursor.execute('SELECT user_id, perfume_id FROM parfumello_user_favorite_perfumes')
        old_favorites = {}
        for user_id, perfume_id in cursor.fetchall():
            old_favorites.setdefault(user_id, []).append(perfume_id)

    # username → old_user_id mapping
    username_to_old_id = {v['username']: k for k, v in old_users.items()}

    for auth_user in AuthUser.objects.all():
        profile, _ = Profile.objects.get_or_create(user=auth_user)

        old_id = username_to_old_id.get(auth_user.username)
        if old_id is not None:
            old_pic = old_users[old_id]['profile_pic']
            if old_pic:
                profile.profile_pic = old_pic
                profile.save()
            for perfume_id in old_favorites.get(old_id, []):
                profile.favorite_perfumes.add(perfume_id)


class Migration(migrations.Migration):

    dependencies = [
        ('parfumello', '0014_alter_userreview_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # 1. Clean up old perfume.review M2M and add the computed average_rating field
        migrations.RemoveField(
            model_name='perfume',
            name='review',
        ),
        migrations.AddField(
            model_name='perfume',
            name='average_rating',
            field=models.FloatField(default=0.0),
        ),
        # 2. Migrate old parfumello.User rows → auth.User, remap review FKs
        migrations.RunPython(migrate_old_users, migrations.RunPython.noop),
        # 3. Now safe to switch the FK on UserReview to auth.User
        migrations.AlterField(
            model_name='userreview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL),
        ),
        # 4. Create the new Profile model
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('favorite_perfumes', models.ManyToManyField(related_name='fans', to='parfumello.perfume')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        # 5. Create profiles for all auth users + carry over favorites
        migrations.RunPython(create_profiles_and_migrate_favorites, migrations.RunPython.noop),
        # 6. Drop the old custom User model
        migrations.DeleteModel(
            name='User',
        ),
    ]
