# Generated by Django 6.0.2 on 2026-04-06 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parfumello', '0015_alter_userreview_user_remove_perfume_review_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfume',
            name='average_rating',
        ),
    ]
