# Generated by Django 6.0.2 on 2026-04-06 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parfumello', '0016_remove_perfume_average_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='favorite_perfumes',
            field=models.ManyToManyField(null=True, related_name='fans', to='parfumello.perfume'),
        ),
    ]
