# Generated by Django 6.0.2 on 2026-04-06 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parfumello', '0017_alter_profile_favorite_perfumes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='favorite_perfumes',
            field=models.ManyToManyField(blank=True, related_name='fans', to='parfumello.perfume'),
        ),
    ]
