# Generated by Django 6.0.2 on 2026-04-17 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parfumello', '0020_perfumenote_alter_perfume_notes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfumenote',
            options={'ordering': ['tier', 'note__name']},
        ),
        migrations.AddField(
            model_name='brand',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='brand_logos/'),
        ),
    ]
