# Generated by Django 6.0.2 on 2026-04-17 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parfumello', '0021_alter_perfumenote_options_brand_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='brand_pics/'),
        ),
    ]
