# Generated by Django 6.0.5 on 2026-06-09 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parfumello", "0022_alter_brand_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="perfume",
            name="kaggle_index",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
